Repository IgrowkerTraining/i005-campers-back, pull requests merged in 2025-04, with the labels that each got.

#51 update code
  prisma/schema.prisma
  src/modules/campings/campings.service.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/users/users.service.ts
Labels: enhancement, sprint 2

#53 Add Reservations Module
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/reservations/dto/create-reservation.dto.ts
  src/modules/reservations/reservations.controller.ts
  src/modules/reservations/reservations.service.ts
Labels: sprint 2

#54 Feature/perfil de camping
  prisma/schema.prisma
  src/modules/campings/campings-search.controller.ts
  src/modules/campings/campings-search.service.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/campings/dto/search-camping.dto.ts
Labels: bug, enhancement, sprint 2

#60 correct syntax
  src/modules/campings/campings-search.service.ts
Labels: bug

#62 improve filtration
  src/modules/campings/campings-search.controller.ts
  src/modules/campings/campings-search.service.ts
Labels: bug, sprint 2

#63 pagination
  src/modules/campings/campings.controller.ts
  src/modules/campings/campings.service.ts
  src/modules/campings/dto/create-camping.dto.ts
Labels: enhancement

#64 Feature/remove unused params
  prisma/migrations/20250415174438_remove_unused_params/migration.sql
  prisma/schema.prisma
  src/modules/campings/campings-search.controller.ts
  src/modules/campings/campings-search.service.ts
  src/modules/campings/campings.module.ts
  src/modules/campings/campings.service.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/campings/dto/search-camping.dto.ts
  src/modules/campings/entities/camping.entity.ts
Labels: enhancement, sprint 2

#73 Feature/reservation confirmation
  .env.example
  prisma/migrations/20250415162801_add_payment_table/migration.sql
  prisma/schema.prisma
  src/common/enums/reservation-status.enum.ts
  src/common/enums/role.enum.ts
  src/common/types/mercadoPago/notification.d.ts
  src/common/types/mercadoPago/payment.d.ts
  src/common/types/reservation-status.d.ts
  src/decorators/roles.decorators.ts
  src/guards/roles.guard.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/mercado-pago/mercado-pago.controller.ts
  src/modules/mercado-pago/mercado-pago.module.ts
  src/modules/mercado-pago/mercado-pago.service.ts
  src/modules/reservations/dto/create-reservation.dto.ts
  src/modules/reservations/dto/update-reservation.dto.ts
  src/modules/reservations/reservations.controller.ts
  src/modules/reservations/reservations.service.ts
  src/modules/users/users.controller.ts
  src/modules/webSockets/camping.gateway.ts
Labels: sprint 3

#80 Feature/reservations cancelation
  .env.example
  prisma/migrations/20250416212645_add_limit_date_refound/migration.sql
  prisma/schema.prisma
  src/modules/mercado-pago/dto/refound-payment.dto.ts
  src/modules/mercado-pago/mercado-pago.controller.ts
  src/modules/mercado-pago/mercado-pago.module.ts
  src/modules/mercado-pago/mercado-pago.service.ts
  src/modules/mercado-pago/payment.repository.ts
  src/modules/reservations/dto/update-reservation.dto.ts
Labels: sprint 3

#83 cloudinary jueves
  src/modules/campings/campings.controller.ts
  src/modules/campings/campings.module.ts
  src/modules/campings/campings.service.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/cloudinary/cloudinary.controller.ts
  src/modules/cloudinary/cloudinary.service.ts
Labels: enhancement

#86 favourite campings
  prisma/migrations/20250417212502_add_favourites/migration.sql
  prisma/schema.prisma
  src/modules/campings/campings.controller.ts
  src/modules/campings/campings.service.ts
  src/modules/campings/dto/favourites-camping.dto.ts
  src/modules/campings/dto/review-response.dto.ts
  src/modules/campings/dto/search-camping.dto.ts
Labels: enhancement, sprint 3

#97 Feature/separate pricing params
  src/main.ts
  src/modules/campings/campings-search.controller.ts
  src/modules/campings/campings-search.service.ts
  src/modules/campings/campings.controller.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/campings/dto/search-camping.dto.ts
Labels: enhancement

#101 update camping by id
  src/modules/campings/campings.controller.ts
  src/modules/campings/campings.service.ts
  src/modules/campings/dto/update-camping.dto.ts
Labels: enhancement

#105 add detailed error messages in camping
  src/common/exception.filter.ts
  src/guards/auth-guard.guard.ts
  src/guards/roles.guard.ts
  src/modules/campings/campings.controller.ts
  src/modules/campings/campings.service.ts
  src/modules/cloudinary/cloudinary.service.ts
Labels: enhancement, sprint 4

#107 Feature/testings
  jest.config.ts
  package.json
  src/common/errorMessages/mercado-pago-messages.ts
  src/common/errorMessages/reservations-error-messages.ts
  src/decorators/is-sanitizated-html.decorator.ts
  src/guards/auth-guard.guard.spec.ts
  src/modules/auth/auth.controller.spec.ts
  src/modules/campings/campings.controller.spec.ts
  src/modules/campings/campings.service.spec.ts
  src/modules/campings/dto/create-camping.dto.ts
  src/modules/cloudinary/cloudinary.controller.spec.ts
  src/modules/mercado-pago/mercado-pago.controller.spec.ts
  src/modules/mercado-pago/mercado-pago.service.spec.ts
  src/modules/mercado-pago/mercado-pago.service.ts
  src/modules/reservations/reservations.controller.spec.ts
  src/modules/reservations/reservations.module.ts
  src/modules/reservations/reservations.service.spec.ts
  src/modules/reservations/reservations.service.ts
  src/modules/users/users.controller.spec.ts
  tsconfig.json
Labels: sprint 4

#110 Feature/error messages
  prisma/migrations/20250423182452_add_unique_name_to_camping/migration.sql
  prisma/migrations/20250423183127_add_unique_name_to_camping/migration.sql
  prisma/schema.prisma
  src/common/errorMessages/camping-error-messages.ts
  src/common/exception.filter.ts
  src/guards/roles.guard.ts
  src/modules/campings/campings-search.controller.ts
  src/modules/campings/campings-search.service.ts
  src/modules/campings/campings.controller.ts
  src/modules/campings/campings.service.ts
  src/prisma/prisma.service.ts
Labels: enhancement, sprint 4

#111 Add integration and Unit testings
  .gitignore
  package-lock.json
  package.json
  src/common/errorMessages/reservations-error-messages.ts
  src/modules/reservations/reservations.service.ts
  test/app.e2e-spec.ts
  test/data.ts
  test/images/cat.jpg
  test/jest-e2e.json
  test/seed-test.ts
  tsconfig.json
Labels: enhancement, sprint 4
